export const TOKEN_FACTORY_ADDRESS =
    "0x83a93500d23Fbc3e82B410aD07A6a9F7A0670D66";

export const AXL_CHAINS: any = {
    base: {
        id: 8453,
        chainId: "base",
        token: "ETH",
    },
    binance: {
        chainId: "binance",
        token: "BNB",
    },
    celo: {
        chainId: "celo",
        token: "CELO",
    },
    ethereum: {
        chainId: "Ethereum",
        token: "ETH",
    },
    fantom: {
        chainId: "Fantom",
        token: "FTM",
    },
    linea: {
        chainId: "linea",
        token: "ETH",
    },
    scroll: {
        chainId: "scroll",
        token: "ETH",
    },
    polygon: {
        chainId: "Polygon",
        token: "MATIC",
    },
    optimism: {
        id: 10,
        chainId: "optimism",
        token: "ETH",
    },
    mantle: {
        chainId: "mantle",
        token: "MNT",
    },
};
export const TOKEN_FACTORY_ABI = [
    {
        inputs: [
            {
                internalType: "address",
                name: "interchainTokenService_",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [
            { internalType: "address", name: "tokenAddress", type: "address" },
        ],
        name: "GatewayToken",
        type: "error",
    },
    { inputs: [], name: "InvalidChainName", type: "error" },
    { inputs: [], name: "InvalidCodeHash", type: "error" },
    { inputs: [], name: "InvalidImplementation", type: "error" },
    { inputs: [], name: "InvalidOwner", type: "error" },
    { inputs: [], name: "InvalidOwnerAddress", type: "error" },
    { inputs: [], name: "MulticallFailed", type: "error" },
    {
        inputs: [{ internalType: "address", name: "minter", type: "address" }],
        name: "NotMinter",
        type: "error",
    },
    {
        inputs: [{ internalType: "address", name: "operator", type: "address" }],
        name: "NotOperator",
        type: "error",
    },
    { inputs: [], name: "NotOwner", type: "error" },
    { inputs: [], name: "NotProxy", type: "error" },
    { inputs: [], name: "SetupFailed", type: "error" },
    { inputs: [], name: "ZeroAddress", type: "error" },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferStarted",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "newImplementation",
                type: "address",
            },
        ],
        name: "Upgraded",
        type: "event",
    },
    {
        inputs: [],
        name: "acceptOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "tokenAddress", type: "address" },
        ],
        name: "canonicalInterchainTokenId",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "chainNameHash_", type: "bytes32" },
            { internalType: "address", name: "tokenAddress", type: "address" },
        ],
        name: "canonicalInterchainTokenSalt",
        outputs: [{ internalType: "bytes32", name: "salt", type: "bytes32" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [],
        name: "chainNameHash",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "contractId",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "salt", type: "bytes32" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "symbol", type: "string" },
            { internalType: "uint8", name: "decimals", type: "uint8" },
            { internalType: "uint256", name: "initialSupply", type: "uint256" },
            { internalType: "address", name: "minter", type: "address" },
        ],
        name: "deployInterchainToken",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "originalChain", type: "string" },
            {
                internalType: "address",
                name: "originalTokenAddress",
                type: "address",
            },
            { internalType: "string", name: "destinationChain", type: "string" },
            { internalType: "uint256", name: "gasValue", type: "uint256" },
        ],
        name: "deployRemoteCanonicalInterchainToken",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "originalChainName", type: "string" },
            { internalType: "bytes32", name: "salt", type: "bytes32" },
            { internalType: "address", name: "minter", type: "address" },
            { internalType: "string", name: "destinationChain", type: "string" },
            { internalType: "uint256", name: "gasValue", type: "uint256" },
        ],
        name: "deployRemoteInterchainToken",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "gateway",
        outputs: [
            { internalType: "contract IAxelarGateway", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "implementation",
        outputs: [
            { internalType: "address", name: "implementation_", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "deployer", type: "address" },
            { internalType: "bytes32", name: "salt", type: "bytes32" },
        ],
        name: "interchainTokenAddress",
        outputs: [
            { internalType: "address", name: "tokenAddress", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "deployer", type: "address" },
            { internalType: "bytes32", name: "salt", type: "bytes32" },
        ],
        name: "interchainTokenId",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "chainNameHash_", type: "bytes32" },
            { internalType: "address", name: "deployer", type: "address" },
            { internalType: "bytes32", name: "salt", type: "bytes32" },
        ],
        name: "interchainTokenSalt",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [],
        name: "interchainTokenService",
        outputs: [
            {
                internalType: "contract IInterchainTokenService",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes[]", name: "data", type: "bytes[]" }],
        name: "multicall",
        outputs: [{ internalType: "bytes[]", name: "results", type: "bytes[]" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "owner_", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "pendingOwner",
        outputs: [{ internalType: "address", name: "owner_", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "proposeOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "tokenAddress", type: "address" },
        ],
        name: "registerCanonicalInterchainToken",
        outputs: [{ internalType: "bytes32", name: "tokenId", type: "bytes32" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
        name: "setup",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "newImplementation", type: "address" },
            {
                internalType: "bytes32",
                name: "newImplementationCodeHash",
                type: "bytes32",
            },
            { internalType: "bytes", name: "params", type: "bytes" },
        ],
        name: "upgrade",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export const TOKEN_ABI = [
    {
        inputs: [
            {
                internalType: "address",
                name: "interchainTokenServiceAddress",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    { inputs: [], name: "AlreadyInitialized", type: "error" },
    { inputs: [], name: "InterchainTokenServiceAddressZero", type: "error" },
    { inputs: [], name: "InvalidAccount", type: "error" },
    {
        inputs: [
            { internalType: "address", name: "fromAccount", type: "address" },
            { internalType: "address", name: "toAccount", type: "address" },
            { internalType: "uint256", name: "accountRoles", type: "uint256" },
        ],
        name: "InvalidProposedRoles",
        type: "error",
    },
    { inputs: [], name: "InvalidS", type: "error" },
    { inputs: [], name: "InvalidSignature", type: "error" },
    { inputs: [], name: "InvalidV", type: "error" },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint256", name: "accountRoles", type: "uint256" },
        ],
        name: "MissingAllRoles",
        type: "error",
    },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint256", name: "accountRoles", type: "uint256" },
        ],
        name: "MissingAnyOfRoles",
        type: "error",
    },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint8", name: "role", type: "uint8" },
        ],
        name: "MissingRole",
        type: "error",
    },
    { inputs: [], name: "PermitExpired", type: "error" },
    { inputs: [], name: "TokenIdZero", type: "error" },
    { inputs: [], name: "TokenNameEmpty", type: "error" },
    { inputs: [], name: "TokenSymbolEmpty", type: "error" },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "spender",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "Approval",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "accountRoles",
                type: "uint256",
            },
        ],
        name: "RolesAdded",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "fromAccount",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "toAccount",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "accountRoles",
                type: "uint256",
            },
        ],
        name: "RolesProposed",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "account",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "accountRoles",
                type: "uint256",
            },
        ],
        name: "RolesRemoved",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "address", name: "from", type: "address" },
            { indexed: true, internalType: "address", name: "to", type: "address" },
            {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
            },
        ],
        name: "Transfer",
        type: "event",
    },
    {
        inputs: [],
        name: "DOMAIN_SEPARATOR",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "fromMinter", type: "address" }],
        name: "acceptMintership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "", type: "address" },
            { internalType: "address", name: "", type: "address" },
        ],
        name: "allowance",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "approve",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "balanceOf",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "burn",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "decimals",
        outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "subtractedValue", type: "uint256" },
        ],
        name: "decreaseAllowance",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint8", name: "role", type: "uint8" },
        ],
        name: "hasRole",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "addedValue", type: "uint256" },
        ],
        name: "increaseAllowance",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "bytes32", name: "tokenId_", type: "bytes32" },
            { internalType: "address", name: "minter", type: "address" },
            { internalType: "string", name: "tokenName", type: "string" },
            { internalType: "string", name: "tokenSymbol", type: "string" },
            { internalType: "uint8", name: "tokenDecimals", type: "uint8" },
        ],
        name: "init",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "interchainTokenId",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "interchainTokenService",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "destinationChain", type: "string" },
            { internalType: "bytes", name: "recipient", type: "bytes" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "bytes", name: "metadata", type: "bytes" },
        ],
        name: "interchainTransfer",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "sender", type: "address" },
            { internalType: "string", name: "destinationChain", type: "string" },
            { internalType: "bytes", name: "recipient", type: "bytes" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "bytes", name: "metadata", type: "bytes" },
        ],
        name: "interchainTransferFrom",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "addr", type: "address" }],
        name: "isMinter",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "mint",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "name",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "nameHash",
        outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "nonces",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "issuer", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "deadline", type: "uint256" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
        ],
        name: "permit",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "minter_", type: "address" }],
        name: "proposeMintership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "symbol",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalSupply",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "recipient", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "transfer",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "sender", type: "address" },
            { internalType: "address", name: "recipient", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "transferFrom",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "minter_", type: "address" }],
        name: "transferMintership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];